# Generated by Django 4.1.7 on 2023-08-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('raridade', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=3)),
            ],
        ),
    ]
